# Generated by Django 5.2.15 on 2026-06-18 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lodge", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="address",
            field=models.TextField(blank=True),
        ),
    ]
