# Generated by Django 5.2.15 on 2026-06-18 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lodge", "0002_property_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="check_in_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="check_out_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
    ]
