# Generated by Django 5.2.15 on 2026-06-18 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lodge", "0003_property_check_in_time_property_check_out_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
