# Generated by Django 5.2.15 on 2026-06-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lodge", "0005_feature_property_features_room_roomimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("percentage", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
