# Generated by Django 5.2.15 on 2026-06-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lodge", "0006_student"),
    ]

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=10
                    ),
                ),
                (
                    "sport",
                    models.CharField(
                        choices=[
                            ("Cricket", "Cricket"),
                            ("Football", "Football"),
                            ("Kabaddi", "Kabaddi"),
                            ("Hockey", "Hockey"),
                        ],
                        max_length=50,
                    ),
                ),
                ("team_name", models.CharField(max_length=100)),
                ("jersey_number", models.IntegerField()),
                ("position", models.CharField(max_length=50)),
                ("matches_played", models.IntegerField(default=0)),
                ("total_runs", models.IntegerField(default=0)),
                ("wickets", models.IntegerField(default=0)),
                ("country", models.CharField(max_length=100)),
                ("height", models.DecimalField(decimal_places=2, max_digits=4)),
                ("weight", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="player_images/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
