# Generated by Django 5.2.15 on 2026-06-23 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lodge", "0007_player"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Player",
        ),
        migrations.DeleteModel(
            name="Student",
        ),
    ]
