# Generated by Django 5.2.15 on 2026-08-02 08:24

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    Property = apps.get_model("lodge", "Property")
    for property_obj in Property.objects.all():
        if property_obj.slug:
            continue
        base_slug = slugify(property_obj.name) or "property"
        slug = base_slug
        counter = 1
        while Property.objects.filter(slug=slug).exclude(pk=property_obj.pk).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1
        property_obj.slug = slug
        property_obj.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ("lodge", "0008_delete_player_delete_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
    ]
