# Generated by Django 5.2.15 on 2026-08-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lodge", "0008_delete_player_delete_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
