# Generated by Django 5.2.15 on 2026-08-01 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TripPlanRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("starting_location", models.CharField(max_length=120)),
                ("destination", models.CharField(max_length=120)),
                ("departure_date", models.DateField()),
                ("duration_days", models.PositiveIntegerField()),
                ("duration_nights", models.PositiveIntegerField()),
                ("travelers", models.PositiveIntegerField()),
                (
                    "group_type",
                    models.CharField(
                        choices=[
                            ("solo", "Solo"),
                            ("couple", "Couple"),
                            ("family", "Family"),
                            ("boys", "Boys Group"),
                            ("girls", "Girls Group"),
                            ("mixed", "Mixed Group"),
                            ("corporate", "Corporate Group"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "travel_mode",
                    models.CharField(
                        choices=[
                            ("bus", "Bus"),
                            ("train", "Train"),
                            ("flight", "Flight"),
                            ("lodgehub_car", "LodgeHub Car Service"),
                            ("private_bus", "Private Travels"),
                            ("self_drive", "Self Drive"),
                        ],
                        max_length=24,
                    ),
                ),
                ("budget", models.CharField(blank=True, max_length=80)),
                ("leader_name", models.CharField(max_length=120)),
                ("leader_phone", models.CharField(max_length=32)),
                ("notes", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
